groupName: cert-manager.webhook.transip

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: quanby/cert-manager-webhook-transip
  tag: latest
  privateRegistrySecretName: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 64Mi
  # requests:
  #  cpu: 100m
  #  memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}
